### ISSUE TITLE
statistic page can't load js & css files

### ISSUE THREAD

**Issue by Tongboy** [davydovanton/sidekiq-statistic#101]
Trying to get the gem running against sidekiq 4.2.2 on a rails 4.2.7.1 app

The statistics page is visible on the web interface of sidekiq but when clicked on it renders incompletely - the css & js file requests to the server return a 500 error with the top of the stack trace saying `NameError - uninitialized constant Sidekiq::WebAction::CONTENT_TYPE:`

any help is much appreciated

**Comment by mperham** [comment]
Try 4.2.3.

**Comment by Tongboy** [comment]
That fixed the 500's - thank you sir!

Now i'm getting some javascript errors `typeError: Cannot read property 'draw' of undefined' & 'typeError: Cannot read property of 'update' of undefined'

```javascript
        reflow: function() {
            var t = e.extend({
                height: this.chart.height,
                width: this.chart.width
            });
            this.scale.update(t) //here
        },
        draw: function(t) {
            var i = t || 1;
            this.clear();
            var s = this.chart.ctx
              , n = function(t) {
                return null !== t.value
            }
              , o = function(t, i, s) {
                return e.findNextWhere(i, n, s) || t
            }
              , a = function(t, i, s) {
                return e.findPreviousWhere(i, n, s) || t
            }
            ;
            this.scale.draw(i), // and here
```

**Comment by Tongboy** [comment]
Never mind! everything started working fine once there was at least one job that had processed since sidekiq-statistic was enabled.

**Comment by alexandru-calinoiu** [comment]
I am getting the same issue on a rails api project, my gem versions are:

rails (4.2.7.1)
rails-api (0.4.0

```
NameError (uninitialized constant Sidekiq::WebAction::CONTENT_TYPE):
  app/middleware/catch_json_parse_errors.rb:8:in `call'
  appsignal (1.3.6) lib/appsignal/rack/rails_instrumentation.rb:15:in `call'


  Rendered /home/calin/.rvm/gems/ruby-2.3.1@.mauka/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.9ms)
  Rendered /home/calin/.rvm/gems/ruby-2.3.1@.mauka/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendered /home/calin/.rvm/gems/ruby-2.3.1@.mauka/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /home/calin/.rvm/gems/ruby-2.3.1@.mauka/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (15.7ms)
```
