### ISSUE TITLE
String can't be coerced into Float

### ISSUE THREAD

**Issue by Daniel-ltw** [davydovanton/sidekiq-statistic#105]
```
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/runtime.rb:40:in `+'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/runtime.rb:40:in `each'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/runtime.rb:40:in `inject'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/runtime.rb:40:in `average_runtime'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/runtime.rb:15:in `values_hash'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/workers.rb:13:in `block in display'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/workers.rb:7:in `map'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/statistic/workers.rb:7:in `display'
23:46:56 web.1     | 	/usr/local/bundle/gems/sidekiq-statistic-1.2.0/lib/sidekiq/statistic/web_extension.rb:32:in `block in registered'
```

**Comment by PanfilovDenis** [comment]
+1

**Comment by Daniel-ltw** [comment]
undefined method `/' for "9.79431929480901e-07":String

Certain statistics are stored as a string value and now could not be converted into a float or for the case above is not convert from a string before the divide happens.

**Comment by Daniel-ltw** [comment]
Could be something to do with

```ruby
      def total_runtime
        values(:total_time).map(&:to_f).inject(:+) || 0.0
      end

      def average_runtime
        averages = values(:average_time)
        count = averages.count
        return 0.0 if count == 0
        averages.inject(:+) / count
      end
```

**Comment by davydovanton** [comment]
I think we should use `.map(&:to_f)` for `#average_runtime` method too. @Daniel-ltw could you create PR and add some tests for this case? Thanks!

**Comment by Daniel-ltw** [comment]
How about the case for the title of the issue? 

Could there be values that are strings but can't be converted into float value?

**Comment by davydovanton** [comment]
Hm, good question. Now I can't imagine values for this case. Do you have any ideas?

**Comment by Daniel-ltw** [comment]
Not sure too. 

Maybe, it could be related. 

Will attempt to get this pull request through and see how that goes.

**Comment by davydovanton** [comment]
fixed by @Daniel-ltw 🎉

**Comment by Daniel-ltw** [comment]
When is this going to be release to rubygems?
