### ISSUE TITLE
Warning from Redis

### ISSUE THREAD

**Issue by danielgomezrico** [davydovanton/sidekiq-statistic#186]
Im getting this warning everytime a job is proccessed on sidekiq:

```ruby
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.pipelined do
  redis.get("key")
end

should be replaced by

redis.pipelined do |pipeline|
  pipeline.get("key")
end

(called from /Users/xxxxxxxx/.rvm/gems/ruby-2.6.8@xxxxxxx/gems/sidekiq-statistic-1.4.0/lib/sidekiq/statistic/middleware.rb:40:in `block in save_entry_for_worker'}
```

**Comment by t1ll** [comment]
Same here - i guess the issue still exists

**Comment by reservedmuffin** [comment]
+1

Environment:
**- sidekiq 6.5.6
- sidekiq-statistic 1.4.0
- redis 4.8.0**

Error
```
Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.

redis.multi do
  redis.get("key")
end

should be replaced by

redis.multi do |pipeline|
  pipeline.get("key")
end

(called from /usr/local/bundle/gems/sidekiq-statistic-1.4.0/lib/sidekiq/statistic/middleware.rb:40:in `block in save_entry_for_worker'}"
```

**Comment by reservedmuffin** [comment]
I can see that there are changes to fix that in [the latest (2.0.0) release ](https://github.com/davydovanton/sidekiq-statistic/pull/165/files). But it's not available on the RubyGems. Why is it so?
