### ISSUE TITLE
Problem with Sidekiq 7

### ISSUE THREAD

**Issue by jcoyne** [davydovanton/sidekiq-statistic#188]
```
NoMethodError: undefined method `value' for 4:Integer
[GEM_ROOT]/gems/sidekiq-statistic-1.4.0/lib/sidekiq/statistic/middleware.rb:52:in `block in save_entry_for_worker' 
[GEM_ROOT]/gems/sidekiq-7.0.0/lib/sidekiq/capsule.rb:85:in `block in redis' 
...
```

This is here: https://github.com/davydovanton/sidekiq-statistic/blob/v1.4.0/lib/sidekiq/statistic/middleware.rb#L52

**Comment by wenderjean** [comment]
Closing this issue once It is addressed by #189
