### ISSUE TITLE
ArgumentError - comparison of String with 0.027 failed

### ISSUE THREAD

**Issue by mateusg** [davydovanton/sidekiq-statistic#76]
Hey guys. I came across this error today:

```
App 9754 stderr: 2015-09-23 17:37:00 - ArgumentError - comparison of String with 0.027 failed:
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/runtime.rb:25:in `each'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/runtime.rb:25:in `min'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/runtime.rb:25:in `min_runtime'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/runtime.rb:14:in `values_hash'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/workers.rb:13:in `block in display'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/workers.rb:7:in `map'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/statistic/workers.rb:7:in `display'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/side
kiq-statistic-1.1.0/lib/sidekiq/statistic/web_extension.rb:32:in `block in registered'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
App 9754 stderr:        /home/user/apps/myapp/shared/bundle/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
```

I'm using:
- Sinatra 1.4.6
- ruby 2.1.2p95
- Sidekiq 3.4.1
- Sidekiq statistic 1.1.0
- Sidekiq failures 0.4.2

Any idea what could it be? I'll see if I can take a look at the code this weekend.

**Comment by davydovanton** [comment]
Hello, I think, that you have a sting in you `min_time` array. Can you display what you have in redis for this worker? (`<Data>:<WorkerName>:timeslist` range in redis )

**Comment by knightq** [comment]
Any release plan for this?

**Comment by davydovanton** [comment]
@knightq hey. I'll create release at the end of this week :)

I have so many tasks in other projects, sorry 😞

**Comment by knightq** [comment]
Don't worry, we must be grateful to people like you who help all of us working better with ruby & sidekiq!

Thank you very much for your effort on this, Anton!
